version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ssl-proxy
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/SchoolServer/Software/dist:/usr/share/nginx/html:ro
    restart: always
